// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Real.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ApuracaoMensalDeFinancasPorCategoriaFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt-br"), "Features", "Apuração Mensal de Finanças por Categoria", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "ApuracaoMensalPorCategoria.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 5
#line hidden
            global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                        "Nome"});
            table1.AddRow(new string[] {
                        "Salário"});
#line 6
 await testRunner.GivenAsync("que existe as seguintes categorias de receitas:", ((string)(null)), table1, "Dado ");
#line hidden
            global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                        "Nome"});
            table2.AddRow(new string[] {
                        "Roupa"});
            table2.AddRow(new string[] {
                        "Mercado"});
            table2.AddRow(new string[] {
                        "Refeição"});
#line 9
 await testRunner.GivenAsync("que existe as seguintes categorias de despesas:", ((string)(null)), table2, "Dado ");
#line hidden
            global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                        "Nome"});
            table3.AddRow(new string[] {
                        "Ca Nubank"});
            table3.AddRow(new string[] {
                        "Cartão C6"});
#line 14
 await testRunner.AndAsync("que existe as seguintes contas de crédito a pagar:", ((string)(null)), table3, "E ");
#line hidden
            global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                        "Nome"});
            table4.AddRow(new string[] {
                        "Carteira_"});
#line 18
 await testRunner.AndAsync("que existe as seguintes contas de débito:", ((string)(null)), table4, "E ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/ApuracaoMensalPorCategoria.feature.ndjson", 3);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Apurar finanças por categoria do mês em regime de competência")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Apurar finanças por categoria do mês em regime de competência")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Apuração Mensal de Finanças por Categoria")]
        public async global::System.Threading.Tasks.Task ApurarFinancasPorCategoriaDoMesEmRegimeDeCompetencia()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Apurar finanças por categoria do mês em regime de competência", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A apuração mensal de finanças por categoria pode ser feita em regime de competênc" +
                    "ia", null, tagsOfRule);
#line 24
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Conta",
                            "Competência",
                            "Data",
                            "Categoria",
                            "Descrição",
                            "Valor",
                            "Tipo"});
                table5.AddRow(new string[] {
                            "Carteira_",
                            "02/02/2025",
                            "02/02/2025",
                            "Salário",
                            "Depósito   _",
                            "200,00",
                            "Receita"});
#line 25
 await testRunner.GivenAsync("que existe as seguintes finanças à vista:", ((string)(null)), table5, "Dado ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Conta",
                            "Competência",
                            "Data",
                            "Categoria",
                            "Descrição",
                            "Valor",
                            "Tipo"});
                table6.AddRow(new string[] {
                            "Cartão C6",
                            "28/12/2024",
                            "10/03/2025",
                            "Roupa",
                            "Renner",
                            "-74,90",
                            "Despesa"});
                table6.AddRow(new string[] {
                            "Cartão C6",
                            "04/02/2025",
                            "10/03/2025",
                            "Mercado",
                            "Fastmarket",
                            "-09,49",
                            "Despesa"});
                table6.AddRow(new string[] {
                            "Cartão C6",
                            "13/02/2025",
                            "10/03/2025",
                            "Mercado",
                            "Supermercado",
                            "-49,87",
                            "Despesa"});
                table6.AddRow(new string[] {
                            "Cartão C6",
                            "06/02/2025",
                            "10/03/2025",
                            "Refeição",
                            "Almoço - Bar",
                            "-38,00",
                            "Despesa"});
#line 28
 await testRunner.AndAsync("que existe as seguintes finanças a prazo:", ((string)(null)), table6, "E ");
#line hidden
#line 34
 await testRunner.WhenAsync("eu apurar as finanças por categoria do mês de \'dezembro\' de 2024 em regime de com" +
                        "petência", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 35
 await testRunner.ThenAsync("a apuração mensal de finanças por categoria deverá ter 0,00 de receitas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 36
 await testRunner.AndAsync("a apuração mensal de finanças por categoria deverá ter -74,90 de despesas", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 37
 await testRunner.AndAsync("a apuração mensal de finanças por categoria deverá ter -74,90 de saldo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 38
 await testRunner.AndAsync("a apuração mensal de finanças por categoria deverá ter 0,00 de saldo acumulado", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 39
 await testRunner.AndAsync("a apuração mensal de finanças por categoria deverá ter -74,90 de saldo total", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Total"});
#line 40
 await testRunner.AndAsync("a apuração mensal de finanças por categoria deverá ter as seguintes receitas:", ((string)(null)), table7, "E ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Total"});
                table8.AddRow(new string[] {
                            "Roupa",
                            "-74,90"});
#line 42
 await testRunner.AndAsync("a apuração mensal de finanças por categoria deverá ter as seguintes despesas:", ((string)(null)), table8, "E ");
#line hidden
#line 45
 await testRunner.WhenAsync("eu apurar as finanças por categoria do mês de \'fevereiro\' de 2025 em regime de co" +
                        "mpetência", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 46
 await testRunner.ThenAsync("a apuração mensal de finanças por categoria deverá ter 200,00 de receitas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 47
 await testRunner.AndAsync("a apuração mensal de finanças por categoria deverá ter -97,36 de despesas", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 48
 await testRunner.AndAsync("a apuração mensal de finanças por categoria deverá ter 102,64 de saldo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 49
 await testRunner.AndAsync("a apuração mensal de finanças por categoria deverá ter -74,90 de saldo acumulado", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 50
 await testRunner.AndAsync("a apuração mensal de finanças por categoria deverá ter 27,74 de saldo total", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Total"});
                table9.AddRow(new string[] {
                            "Salário",
                            "200,00"});
#line 51
 await testRunner.AndAsync("a apuração mensal de finanças por categoria deverá ter as seguintes receitas:", ((string)(null)), table9, "E ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Total"});
                table10.AddRow(new string[] {
                            "Mercado",
                            "-59,36"});
                table10.AddRow(new string[] {
                            "Refeição",
                            "-38,00"});
#line 54
 await testRunner.AndAsync("a apuração mensal de finanças por categoria deverá ter as seguintes despesas:", ((string)(null)), table10, "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
