// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Real.Data;

#nullable disable

namespace Real.Data.Migrations
{
    [DbContext(typeof(RealDbContext))]
    [Migration("20251228161547_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Real.Models.Apuracao", b =>
                {
                    b.Property<DateOnly>("Competencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ValorPorCompetencia")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorPorData")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Competencia");

                    b.ToTable("Apuracoes");
                });

            modelBuilder.Entity("Real.Models.Categoria", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AplicaDespesa")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AplicaReceita")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoriaPaiId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPaiId");

                    b.HasIndex("IconId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = "salario               ",
                            AplicaDespesa = false,
                            AplicaReceita = true,
                            IconId = "cash-coin",
                            Nome = "Salário",
                            Ordem = 0
                        },
                        new
                        {
                            Id = "balanco               ",
                            AplicaDespesa = false,
                            AplicaReceita = true,
                            IconId = "currency-dollar",
                            Nome = "Balanço",
                            Ordem = 1
                        },
                        new
                        {
                            Id = "imposto               ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "coin",
                            Nome = "Imposto",
                            Ordem = 2
                        },
                        new
                        {
                            Id = "multa                 ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "currency-dollar",
                            Nome = "Multa",
                            Ordem = 3
                        },
                        new
                        {
                            Id = "juros                 ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "currency-dollar",
                            Nome = "Juros",
                            Ordem = 4
                        },
                        new
                        {
                            Id = "taxa                  ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "currency-dollar",
                            Nome = "Taxa",
                            Ordem = 5
                        },
                        new
                        {
                            Id = "emprestimo            ",
                            AplicaDespesa = true,
                            AplicaReceita = true,
                            IconId = "cash",
                            Nome = "Empréstimo",
                            Ordem = 6
                        },
                        new
                        {
                            Id = "seguro                ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "house-lock",
                            Nome = "Seguro",
                            Ordem = 7
                        },
                        new
                        {
                            Id = "reserva               ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "piggy-bank",
                            Nome = "Reserva",
                            Ordem = 8
                        },
                        new
                        {
                            Id = "casa                  ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "house-heart",
                            Nome = "Casa",
                            Ordem = 9
                        },
                        new
                        {
                            Id = "moradia               ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "casa                  ",
                            IconId = "house-heart",
                            Nome = "Moradia",
                            Ordem = 10
                        },
                        new
                        {
                            Id = "aluguel               ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "moradia               ",
                            IconId = "house-heart",
                            Nome = "Aluguel",
                            Ordem = 11
                        },
                        new
                        {
                            Id = "condominio            ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "moradia               ",
                            IconId = "building",
                            Nome = "Condomínio",
                            Ordem = 12
                        },
                        new
                        {
                            Id = "agua                  ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "casa                  ",
                            IconId = "droplet",
                            Nome = "Água",
                            Ordem = 13
                        },
                        new
                        {
                            Id = "luz                   ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "casa                  ",
                            IconId = "lightbulb",
                            Nome = "Luz",
                            Ordem = 14
                        },
                        new
                        {
                            Id = "gas                   ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "casa                  ",
                            IconId = "fire",
                            Nome = "Gás",
                            Ordem = 15
                        },
                        new
                        {
                            Id = "telefone              ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "casa                  ",
                            IconId = "telephone",
                            Nome = "Telefone",
                            Ordem = 16
                        },
                        new
                        {
                            Id = "internet              ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "casa                  ",
                            IconId = "router",
                            Nome = "Internet",
                            Ordem = 17
                        },
                        new
                        {
                            Id = "celular               ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "phone",
                            Nome = "Celular",
                            Ordem = 18
                        },
                        new
                        {
                            Id = "stream                ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "music-player",
                            Nome = "Stream",
                            Ordem = 19
                        },
                        new
                        {
                            Id = "storage               ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "cloud-arrow-up",
                            Nome = "Storage",
                            Ordem = 20
                        },
                        new
                        {
                            Id = "assinatura            ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "cloud",
                            Nome = "Assinatura",
                            Ordem = 21
                        },
                        new
                        {
                            Id = "profissional          ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "briefcase",
                            Nome = "Profissional",
                            Ordem = 22
                        },
                        new
                        {
                            Id = "dominio               ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "globe-americas",
                            Nome = "Domínio",
                            Ordem = 23
                        },
                        new
                        {
                            Id = "contabilidade         ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "briefcase",
                            Nome = "Contabilidade",
                            Ordem = 24
                        },
                        new
                        {
                            Id = "educacao              ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "backpack",
                            Nome = "Educação",
                            Ordem = 25
                        },
                        new
                        {
                            Id = "livro                 ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "book",
                            Nome = "Livro",
                            Ordem = 26
                        },
                        new
                        {
                            Id = "saude                 ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "heart-pulse",
                            Nome = "Saúde",
                            Ordem = 27
                        },
                        new
                        {
                            Id = "plano-de-saude        ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "saude                 ",
                            IconId = "heart-pulse",
                            Nome = "Plano de Saúde",
                            Ordem = 28
                        },
                        new
                        {
                            Id = "plano-odontologico    ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "saude                 ",
                            IconId = "heart-pulse",
                            Nome = "Plano Odontológico",
                            Ordem = 29
                        },
                        new
                        {
                            Id = "medico                ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "saude                 ",
                            IconId = "heart-pulse",
                            Nome = "Médico",
                            Ordem = 30
                        },
                        new
                        {
                            Id = "dentista              ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "saude                 ",
                            IconId = "heart-pulse",
                            Nome = "Dentista",
                            Ordem = 31
                        },
                        new
                        {
                            Id = "pscicologo            ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "saude                 ",
                            IconId = "heart-pulse",
                            Nome = "Pscicólogo",
                            Ordem = 32
                        },
                        new
                        {
                            Id = "academia              ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "heart-pulse",
                            Nome = "Academia",
                            Ordem = 33
                        },
                        new
                        {
                            Id = "farmacia              ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "shop",
                            Nome = "Farmácia",
                            Ordem = 34
                        },
                        new
                        {
                            Id = "medicamento           ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "saude                 ",
                            IconId = "capsule",
                            Nome = "Medicamento",
                            Ordem = 35
                        },
                        new
                        {
                            Id = "suplemento            ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "saude                 ",
                            IconId = "capsule",
                            Nome = "Suplemento",
                            Ordem = 36
                        },
                        new
                        {
                            Id = "compra                ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "bag",
                            Nome = "Compra",
                            Ordem = 37
                        },
                        new
                        {
                            Id = "mercado               ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "cart4",
                            Nome = "Mercado",
                            Ordem = 38
                        },
                        new
                        {
                            Id = "leite-de-formula      ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "cart4",
                            Nome = "Leite de Fórmula",
                            Ordem = 39
                        },
                        new
                        {
                            Id = "refeicao              ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "egg-fried",
                            Nome = "Refeição",
                            Ordem = 40
                        },
                        new
                        {
                            Id = "restaurante           ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "shop",
                            Nome = "Restaurante",
                            Ordem = 41
                        },
                        new
                        {
                            Id = "padaria               ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "shop",
                            Nome = "Padaria",
                            Ordem = 42
                        },
                        new
                        {
                            Id = "lanche                ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "shop",
                            Nome = "Lanche",
                            Ordem = 43
                        },
                        new
                        {
                            Id = "hamburger             ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "lanche                ",
                            IconId = "shop",
                            Nome = "Hamburger",
                            Ordem = 44
                        },
                        new
                        {
                            Id = "pizza                 ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "lanche                ",
                            IconId = "shop",
                            Nome = "Pizza",
                            Ordem = 45
                        },
                        new
                        {
                            Id = "sorvete               ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "lanche                ",
                            IconId = "shop",
                            Nome = "Sorvete",
                            Ordem = 46
                        },
                        new
                        {
                            Id = "pet                   ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "shop",
                            Nome = "Pet",
                            Ordem = 47
                        },
                        new
                        {
                            Id = "roupa                 ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "shop",
                            Nome = "Roupa",
                            Ordem = 48
                        },
                        new
                        {
                            Id = "presente              ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "shop",
                            Nome = "Presente",
                            Ordem = 49
                        },
                        new
                        {
                            Id = "brinquedo             ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "shop",
                            Nome = "Brinquedo",
                            Ordem = 50
                        },
                        new
                        {
                            Id = "beleza                ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "shop",
                            Nome = "Beleza",
                            Ordem = 51
                        },
                        new
                        {
                            Id = "salao-de-beleza       ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "beleza                ",
                            IconId = "shop",
                            Nome = "Salão de Beleza",
                            Ordem = 52
                        },
                        new
                        {
                            Id = "barbeiro              ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "beleza                ",
                            IconId = "shop",
                            Nome = "Barbeiro",
                            Ordem = 53
                        },
                        new
                        {
                            Id = "carro                 ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "car-front",
                            Nome = "Carro",
                            Ordem = 54
                        },
                        new
                        {
                            Id = "combustivel           ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "fuel-pump",
                            Nome = "Combustível",
                            Ordem = 55
                        },
                        new
                        {
                            Id = "estacionamento        ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "p-circle",
                            Nome = "Estacionamento",
                            Ordem = 56
                        },
                        new
                        {
                            Id = "pedagio               ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "car-front",
                            Nome = "Pedágio",
                            Ordem = 57
                        },
                        new
                        {
                            Id = "lavajato              ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "car-front",
                            Nome = "Lavajato",
                            Ordem = 58
                        },
                        new
                        {
                            Id = "transporte            ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "bus-front",
                            Nome = "Transporte",
                            Ordem = 59
                        },
                        new
                        {
                            Id = "passagem              ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "transporte            ",
                            IconId = "bus-front",
                            Nome = "Passagem",
                            Ordem = 60
                        },
                        new
                        {
                            Id = "taxi                  ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "transporte            ",
                            IconId = "taxi-front",
                            Nome = "Taxi",
                            Ordem = 61
                        },
                        new
                        {
                            Id = "lazer                 ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "emoji-sunglasses",
                            Nome = "Lazer",
                            Ordem = 62
                        },
                        new
                        {
                            Id = "cinema                ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            CategoriaPaiId = "lazer                 ",
                            IconId = "film",
                            Nome = "Cinema",
                            Ordem = 63
                        },
                        new
                        {
                            Id = "perfume               ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "flower1",
                            Nome = "Perfume",
                            Ordem = 64
                        },
                        new
                        {
                            Id = "diversos              ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "bookmarks",
                            Nome = "Diversos",
                            Ordem = 65
                        },
                        new
                        {
                            Id = "outros                ",
                            AplicaDespesa = true,
                            AplicaReceita = false,
                            IconId = "bookmark",
                            Nome = "Outros",
                            Ordem = 66
                        });
                });

            modelBuilder.Entity("Real.Models.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pessoa")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoContaId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Contas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0000-4000-8000-000000000000"),
                            Ativa = false,
                            Nome = "Carteira",
                            Ordem = 0,
                            TipoContaId = 0
                        });
                });

            modelBuilder.Entity("Real.Models.Icon", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BiClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BiUnicode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FaClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FaUnicode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Icons");

                    b.HasData(
                        new
                        {
                            Id = "shop",
                            BiClass = "shop",
                            BiUnicode = "",
                            FaClass = "shop",
                            FaUnicode = "",
                            Name = "Shop"
                        },
                        new
                        {
                            Id = "cart4",
                            BiClass = "cart4",
                            BiUnicode = "",
                            FaClass = "cart-shopping",
                            FaUnicode = "",
                            Name = "Cart Shopping"
                        },
                        new
                        {
                            Id = "cash-coin",
                            BiClass = "cash-coin",
                            BiUnicode = "",
                            FaClass = "money-bills",
                            FaUnicode = "",
                            Name = "Cash Coin"
                        },
                        new
                        {
                            Id = "currency-dollar",
                            BiClass = "currency-dollar",
                            BiUnicode = "",
                            FaClass = "dollar-sign",
                            FaUnicode = "$",
                            Name = "Currency Dollar"
                        },
                        new
                        {
                            Id = "coin",
                            BiClass = "coin",
                            BiUnicode = "",
                            FaClass = "coins",
                            FaUnicode = "",
                            Name = "Coin"
                        },
                        new
                        {
                            Id = "cash",
                            BiClass = "cash",
                            BiUnicode = "",
                            FaClass = "money-bill",
                            FaUnicode = "",
                            Name = "Cash"
                        },
                        new
                        {
                            Id = "house-lock",
                            BiClass = "house-lock",
                            BiUnicode = "",
                            FaClass = "house-lock",
                            FaUnicode = "",
                            Name = "House Lock"
                        },
                        new
                        {
                            Id = "piggy-bank",
                            BiClass = "piggy-bank",
                            BiUnicode = "",
                            FaClass = "piggy-bank",
                            FaUnicode = "",
                            Name = "Piggy Bank"
                        },
                        new
                        {
                            Id = "house-heart",
                            BiClass = "house-heart",
                            BiUnicode = "",
                            FaClass = "house-circle-check",
                            FaUnicode = "",
                            Name = "House Heart"
                        },
                        new
                        {
                            Id = "building",
                            BiClass = "building",
                            BiUnicode = "",
                            FaClass = "building",
                            FaUnicode = "",
                            Name = "Building"
                        },
                        new
                        {
                            Id = "droplet",
                            BiClass = "droplet",
                            BiUnicode = "",
                            FaClass = "droplet",
                            FaUnicode = "",
                            Name = "Droplet"
                        },
                        new
                        {
                            Id = "lightbulb",
                            BiClass = "lightbulb",
                            BiUnicode = "",
                            FaClass = "lightbulb",
                            FaUnicode = "",
                            Name = "Lightbulb"
                        },
                        new
                        {
                            Id = "fire",
                            BiClass = "fire",
                            BiUnicode = "",
                            FaClass = "fire",
                            FaUnicode = "",
                            Name = "Fire"
                        },
                        new
                        {
                            Id = "telephone",
                            BiClass = "telephone",
                            BiUnicode = "",
                            FaClass = "phone",
                            FaUnicode = "",
                            Name = "Telephone"
                        },
                        new
                        {
                            Id = "router",
                            BiClass = "router",
                            BiUnicode = "",
                            FaClass = "wifi",
                            FaUnicode = "",
                            Name = "Router"
                        },
                        new
                        {
                            Id = "capsule",
                            BiClass = "capsule",
                            BiUnicode = "",
                            FaClass = "capsules",
                            FaUnicode = "",
                            Name = "Capsule"
                        },
                        new
                        {
                            Id = "taxi-front",
                            BiClass = "taxi-front",
                            BiUnicode = "",
                            FaClass = "taxi",
                            FaUnicode = "",
                            Name = "Taxi Front"
                        },
                        new
                        {
                            Id = "film",
                            BiClass = "film",
                            BiUnicode = "",
                            FaClass = "film",
                            FaUnicode = "",
                            Name = "Film"
                        },
                        new
                        {
                            Id = "phone",
                            BiClass = "phone",
                            BiUnicode = "",
                            FaClass = "mobile-screen",
                            FaUnicode = "",
                            Name = "Phone"
                        },
                        new
                        {
                            Id = "music-player",
                            BiClass = "music-player",
                            BiUnicode = "",
                            FaClass = "music",
                            FaUnicode = "",
                            Name = "Music Player"
                        },
                        new
                        {
                            Id = "cloud-arrow-up",
                            BiClass = "cloud-arrow-up",
                            BiUnicode = "",
                            FaClass = "cloud-arrow-up",
                            FaUnicode = "",
                            Name = "Cloud Arrow Up"
                        },
                        new
                        {
                            Id = "cloud",
                            BiClass = "cloud",
                            BiUnicode = "",
                            FaClass = "cloud",
                            FaUnicode = "",
                            Name = "Cloud"
                        },
                        new
                        {
                            Id = "briefcase",
                            BiClass = "briefcase",
                            BiUnicode = "",
                            FaClass = "briefcase",
                            FaUnicode = "",
                            Name = "Briefcase"
                        },
                        new
                        {
                            Id = "globe-americas",
                            BiClass = "globe-americas",
                            BiUnicode = "",
                            FaClass = "earth-americas",
                            FaUnicode = "",
                            Name = "Globe Americas"
                        },
                        new
                        {
                            Id = "backpack",
                            BiClass = "backpack",
                            BiUnicode = "",
                            FaClass = "graduation-cap",
                            FaUnicode = "",
                            Name = "Backpack"
                        },
                        new
                        {
                            Id = "book",
                            BiClass = "book",
                            BiUnicode = "",
                            FaClass = "book",
                            FaUnicode = "",
                            Name = "Book"
                        },
                        new
                        {
                            Id = "heart-pulse",
                            BiClass = "heart-pulse",
                            BiUnicode = "",
                            FaClass = "heart-pulse",
                            FaUnicode = "",
                            Name = "Heart Pulse"
                        },
                        new
                        {
                            Id = "bag",
                            BiClass = "bag",
                            BiUnicode = "",
                            FaClass = "bag-shopping",
                            FaUnicode = "",
                            Name = "Bag"
                        },
                        new
                        {
                            Id = "egg-fried",
                            BiClass = "egg-fried",
                            BiUnicode = "",
                            FaClass = "utensils",
                            FaUnicode = "",
                            Name = "Egg Fied"
                        },
                        new
                        {
                            Id = "car-front",
                            BiClass = "car-front",
                            BiUnicode = "",
                            FaClass = "car",
                            FaUnicode = "",
                            Name = "Car Front"
                        },
                        new
                        {
                            Id = "fuel-pump",
                            BiClass = "fuel-pump",
                            BiUnicode = "",
                            FaClass = "gas-pump",
                            FaUnicode = "",
                            Name = "Fuel Pump"
                        },
                        new
                        {
                            Id = "p-circle",
                            BiClass = "p-circle",
                            BiUnicode = "",
                            FaClass = "square-parking",
                            FaUnicode = "",
                            Name = "P Circle"
                        },
                        new
                        {
                            Id = "bus-front",
                            BiClass = "bus-front",
                            BiUnicode = "",
                            FaClass = "bus",
                            FaUnicode = "",
                            Name = "Bus Front"
                        },
                        new
                        {
                            Id = "emoji-sunglasses",
                            BiClass = "emoji-sunglasses",
                            BiUnicode = "",
                            FaClass = "champagne-glasses",
                            FaUnicode = "",
                            Name = "Emoji Sunglasses"
                        },
                        new
                        {
                            Id = "flower1",
                            BiClass = "flower1",
                            BiUnicode = "",
                            FaClass = "spray-can-sparkles",
                            FaUnicode = "",
                            Name = "Flower1"
                        },
                        new
                        {
                            Id = "bookmarks",
                            BiClass = "bookmarks",
                            BiUnicode = "",
                            FaClass = "book-bookmark",
                            FaUnicode = "",
                            Name = "Bookmarks"
                        },
                        new
                        {
                            Id = "bookmark",
                            BiClass = "bookmark",
                            BiUnicode = "",
                            FaClass = "bookmark",
                            FaUnicode = "",
                            Name = "Bookmark"
                        });
                });

            modelBuilder.Entity("Real.Models.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Competencia")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EhGrupo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EhParcela")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EhParcelamento")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EhRecorrente")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("GrupoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParcelamentoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecorrenciaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoLancamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoRegistroId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ContaId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("ParcelamentoId");

                    b.ToTable("Lancamentos");

                    b.HasDiscriminator().HasValue("Lancamento");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Real.Models.Recorrencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Competencia")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoFinancaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoLancamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoRecorrenciaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaId");

                    b.ToTable("Recorrencia");
                });

            modelBuilder.Entity("Real.Models.Financa", b =>
                {
                    b.HasBaseType("Real.Models.Lancamento");

                    b.Property<string>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EhPrevisao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoFinancaId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("RecorrenciaId");

                    b.HasDiscriminator().HasValue("Financa");
                });

            modelBuilder.Entity("Real.Models.Grupo", b =>
                {
                    b.HasBaseType("Real.Models.Lancamento");

                    b.HasIndex("RecorrenciaId");

                    b.HasDiscriminator().HasValue("Grupo");
                });

            modelBuilder.Entity("Real.Models.Categoria", b =>
                {
                    b.HasOne("Real.Models.Categoria", "CategoriaPai")
                        .WithMany()
                        .HasForeignKey("CategoriaPaiId");

                    b.HasOne("Real.Models.Icon", "Icon")
                        .WithMany()
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaPai");

                    b.Navigation("Icon");
                });

            modelBuilder.Entity("Real.Models.Lancamento", b =>
                {
                    b.HasOne("Real.Models.Conta", "Conta")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ContaId");

                    b.HasOne("Real.Models.Grupo", "Grupo")
                        .WithMany("Lancamentos")
                        .HasForeignKey("GrupoId");

                    b.HasOne("Real.Models.Lancamento", "Parcelamento")
                        .WithMany("Parcelas")
                        .HasForeignKey("ParcelamentoId");

                    b.Navigation("Conta");

                    b.Navigation("Grupo");

                    b.Navigation("Parcelamento");
                });

            modelBuilder.Entity("Real.Models.Recorrencia", b =>
                {
                    b.HasOne("Real.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("Real.Models.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId");

                    b.Navigation("Categoria");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("Real.Models.Financa", b =>
                {
                    b.HasOne("Real.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("Real.Models.Recorrencia", "Recorrencia")
                        .WithMany("Repeticoes")
                        .HasForeignKey("RecorrenciaId");

                    b.Navigation("Categoria");

                    b.Navigation("Recorrencia");
                });

            modelBuilder.Entity("Real.Models.Grupo", b =>
                {
                    b.HasOne("Real.Models.Recorrencia", "Recorrencia")
                        .WithMany()
                        .HasForeignKey("RecorrenciaId");

                    b.Navigation("Recorrencia");
                });

            modelBuilder.Entity("Real.Models.Conta", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("Real.Models.Lancamento", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("Real.Models.Recorrencia", b =>
                {
                    b.Navigation("Repeticoes");
                });

            modelBuilder.Entity("Real.Models.Grupo", b =>
                {
                    b.Navigation("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
