// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Real.Data;

#nullable disable

namespace Real.Data.Migrations
{
    [DbContext(typeof(RealDbContext))]
    [Migration("20251228214930_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Real.Models.Apuracao", b =>
                {
                    b.Property<DateOnly>("Competencia")
                        .HasColumnType("date");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorPorCompetencia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorPorData")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Competencia");

                    b.ToTable("Apuracoes", "dbo");
                });

            modelBuilder.Entity("Real.Models.Categoria", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AplicaDespesa")
                        .HasColumnType("bit");

                    b.Property<bool>("AplicaReceita")
                        .HasColumnType("bit");

                    b.Property<bool?>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("CategoriaPaiId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IconId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Ordem")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPaiId");

                    b.HasIndex("IconId");

                    b.ToTable("Categorias", "dbo");
                });

            modelBuilder.Entity("Real.Models.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Pessoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoContaId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Contas", "dbo");
                });

            modelBuilder.Entity("Real.Models.Icon", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BiClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BiUnicode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaUnicode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Icons", "dbo");

                    b.HasData(
                        new
                        {
                            Id = "shop",
                            BiClass = "shop",
                            BiUnicode = "",
                            FaClass = "shop",
                            FaUnicode = "",
                            Name = "Shop"
                        },
                        new
                        {
                            Id = "cart4",
                            BiClass = "cart4",
                            BiUnicode = "",
                            FaClass = "cart-shopping",
                            FaUnicode = "",
                            Name = "Cart Shopping"
                        },
                        new
                        {
                            Id = "cash-coin",
                            BiClass = "cash-coin",
                            BiUnicode = "",
                            FaClass = "money-bills",
                            FaUnicode = "",
                            Name = "Cash Coin"
                        },
                        new
                        {
                            Id = "currency-dollar",
                            BiClass = "currency-dollar",
                            BiUnicode = "",
                            FaClass = "dollar-sign",
                            FaUnicode = "$",
                            Name = "Currency Dollar"
                        },
                        new
                        {
                            Id = "coin",
                            BiClass = "coin",
                            BiUnicode = "",
                            FaClass = "coins",
                            FaUnicode = "",
                            Name = "Coin"
                        },
                        new
                        {
                            Id = "cash",
                            BiClass = "cash",
                            BiUnicode = "",
                            FaClass = "money-bill",
                            FaUnicode = "",
                            Name = "Cash"
                        },
                        new
                        {
                            Id = "house-lock",
                            BiClass = "house-lock",
                            BiUnicode = "",
                            FaClass = "house-lock",
                            FaUnicode = "",
                            Name = "House Lock"
                        },
                        new
                        {
                            Id = "piggy-bank",
                            BiClass = "piggy-bank",
                            BiUnicode = "",
                            FaClass = "piggy-bank",
                            FaUnicode = "",
                            Name = "Piggy Bank"
                        },
                        new
                        {
                            Id = "house-heart",
                            BiClass = "house-heart",
                            BiUnicode = "",
                            FaClass = "house-circle-check",
                            FaUnicode = "",
                            Name = "House Heart"
                        },
                        new
                        {
                            Id = "building",
                            BiClass = "building",
                            BiUnicode = "",
                            FaClass = "building",
                            FaUnicode = "",
                            Name = "Building"
                        },
                        new
                        {
                            Id = "droplet",
                            BiClass = "droplet",
                            BiUnicode = "",
                            FaClass = "droplet",
                            FaUnicode = "",
                            Name = "Droplet"
                        },
                        new
                        {
                            Id = "lightbulb",
                            BiClass = "lightbulb",
                            BiUnicode = "",
                            FaClass = "lightbulb",
                            FaUnicode = "",
                            Name = "Lightbulb"
                        },
                        new
                        {
                            Id = "fire",
                            BiClass = "fire",
                            BiUnicode = "",
                            FaClass = "fire",
                            FaUnicode = "",
                            Name = "Fire"
                        },
                        new
                        {
                            Id = "telephone",
                            BiClass = "telephone",
                            BiUnicode = "",
                            FaClass = "phone",
                            FaUnicode = "",
                            Name = "Telephone"
                        },
                        new
                        {
                            Id = "router",
                            BiClass = "router",
                            BiUnicode = "",
                            FaClass = "wifi",
                            FaUnicode = "",
                            Name = "Router"
                        },
                        new
                        {
                            Id = "capsule",
                            BiClass = "capsule",
                            BiUnicode = "",
                            FaClass = "capsules",
                            FaUnicode = "",
                            Name = "Capsule"
                        },
                        new
                        {
                            Id = "taxi-front",
                            BiClass = "taxi-front",
                            BiUnicode = "",
                            FaClass = "taxi",
                            FaUnicode = "",
                            Name = "Taxi Front"
                        },
                        new
                        {
                            Id = "film",
                            BiClass = "film",
                            BiUnicode = "",
                            FaClass = "film",
                            FaUnicode = "",
                            Name = "Film"
                        },
                        new
                        {
                            Id = "phone",
                            BiClass = "phone",
                            BiUnicode = "",
                            FaClass = "mobile-screen",
                            FaUnicode = "",
                            Name = "Phone"
                        },
                        new
                        {
                            Id = "music-player",
                            BiClass = "music-player",
                            BiUnicode = "",
                            FaClass = "music",
                            FaUnicode = "",
                            Name = "Music Player"
                        },
                        new
                        {
                            Id = "cloud-arrow-up",
                            BiClass = "cloud-arrow-up",
                            BiUnicode = "",
                            FaClass = "cloud-arrow-up",
                            FaUnicode = "",
                            Name = "Cloud Arrow Up"
                        },
                        new
                        {
                            Id = "cloud",
                            BiClass = "cloud",
                            BiUnicode = "",
                            FaClass = "cloud",
                            FaUnicode = "",
                            Name = "Cloud"
                        },
                        new
                        {
                            Id = "briefcase",
                            BiClass = "briefcase",
                            BiUnicode = "",
                            FaClass = "briefcase",
                            FaUnicode = "",
                            Name = "Briefcase"
                        },
                        new
                        {
                            Id = "globe-americas",
                            BiClass = "globe-americas",
                            BiUnicode = "",
                            FaClass = "earth-americas",
                            FaUnicode = "",
                            Name = "Globe Americas"
                        },
                        new
                        {
                            Id = "backpack",
                            BiClass = "backpack",
                            BiUnicode = "",
                            FaClass = "graduation-cap",
                            FaUnicode = "",
                            Name = "Backpack"
                        },
                        new
                        {
                            Id = "book",
                            BiClass = "book",
                            BiUnicode = "",
                            FaClass = "book",
                            FaUnicode = "",
                            Name = "Book"
                        },
                        new
                        {
                            Id = "heart-pulse",
                            BiClass = "heart-pulse",
                            BiUnicode = "",
                            FaClass = "heart-pulse",
                            FaUnicode = "",
                            Name = "Heart Pulse"
                        },
                        new
                        {
                            Id = "bag",
                            BiClass = "bag",
                            BiUnicode = "",
                            FaClass = "bag-shopping",
                            FaUnicode = "",
                            Name = "Bag"
                        },
                        new
                        {
                            Id = "egg-fried",
                            BiClass = "egg-fried",
                            BiUnicode = "",
                            FaClass = "utensils",
                            FaUnicode = "",
                            Name = "Egg Fied"
                        },
                        new
                        {
                            Id = "car-front",
                            BiClass = "car-front",
                            BiUnicode = "",
                            FaClass = "car",
                            FaUnicode = "",
                            Name = "Car Front"
                        },
                        new
                        {
                            Id = "fuel-pump",
                            BiClass = "fuel-pump",
                            BiUnicode = "",
                            FaClass = "gas-pump",
                            FaUnicode = "",
                            Name = "Fuel Pump"
                        },
                        new
                        {
                            Id = "p-circle",
                            BiClass = "p-circle",
                            BiUnicode = "",
                            FaClass = "square-parking",
                            FaUnicode = "",
                            Name = "P Circle"
                        },
                        new
                        {
                            Id = "bus-front",
                            BiClass = "bus-front",
                            BiUnicode = "",
                            FaClass = "bus",
                            FaUnicode = "",
                            Name = "Bus Front"
                        },
                        new
                        {
                            Id = "emoji-sunglasses",
                            BiClass = "emoji-sunglasses",
                            BiUnicode = "",
                            FaClass = "champagne-glasses",
                            FaUnicode = "",
                            Name = "Emoji Sunglasses"
                        },
                        new
                        {
                            Id = "flower1",
                            BiClass = "flower1",
                            BiUnicode = "",
                            FaClass = "spray-can-sparkles",
                            FaUnicode = "",
                            Name = "Flower1"
                        },
                        new
                        {
                            Id = "bookmarks",
                            BiClass = "bookmarks",
                            BiUnicode = "",
                            FaClass = "book-bookmark",
                            FaUnicode = "",
                            Name = "Bookmarks"
                        },
                        new
                        {
                            Id = "bookmark",
                            BiClass = "bookmark",
                            BiUnicode = "",
                            FaClass = "bookmark",
                            FaUnicode = "",
                            Name = "Bookmark"
                        });
                });

            modelBuilder.Entity("Real.Models.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Competencia")
                        .HasColumnType("date");

                    b.Property<Guid?>("ContaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("EhGrupo")
                        .HasColumnType("bit");

                    b.Property<bool>("EhParcela")
                        .HasColumnType("bit");

                    b.Property<bool>("EhParcelamento")
                        .HasColumnType("bit");

                    b.Property<bool>("EhRecorrente")
                        .HasColumnType("bit");

                    b.Property<Guid?>("GrupoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("int");

                    b.Property<int?>("Ordem")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParcelamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RecorrenciaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoLancamentoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoRegistroId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ContaId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("ParcelamentoId");

                    b.ToTable("Lancamentos", "dbo");

                    b.HasDiscriminator().HasValue("Lancamento");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Real.Models.Recorrencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoriaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("Competencia")
                        .HasColumnType("date");

                    b.Property<Guid?>("ContaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<int?>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("TipoFinancaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoLancamentoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoRecorrenciaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaId");

                    b.ToTable("Recorrencia", "dbo");
                });

            modelBuilder.Entity("Real.Models.Financa", b =>
                {
                    b.HasBaseType("Real.Models.Lancamento");

                    b.Property<string>("CategoriaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EhPrevisao")
                        .HasColumnType("bit");

                    b.Property<int>("TipoFinancaId")
                        .HasColumnType("int");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("RecorrenciaId");

                    b.HasDiscriminator().HasValue("Financa");
                });

            modelBuilder.Entity("Real.Models.Grupo", b =>
                {
                    b.HasBaseType("Real.Models.Lancamento");

                    b.HasIndex("RecorrenciaId");

                    b.HasDiscriminator().HasValue("Grupo");
                });

            modelBuilder.Entity("Real.Models.Categoria", b =>
                {
                    b.HasOne("Real.Models.Categoria", "CategoriaPai")
                        .WithMany()
                        .HasForeignKey("CategoriaPaiId");

                    b.HasOne("Real.Models.Icon", "Icon")
                        .WithMany()
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaPai");

                    b.Navigation("Icon");
                });

            modelBuilder.Entity("Real.Models.Lancamento", b =>
                {
                    b.HasOne("Real.Models.Conta", "Conta")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ContaId");

                    b.HasOne("Real.Models.Grupo", "Grupo")
                        .WithMany("Lancamentos")
                        .HasForeignKey("GrupoId");

                    b.HasOne("Real.Models.Lancamento", "Parcelamento")
                        .WithMany("Parcelas")
                        .HasForeignKey("ParcelamentoId");

                    b.Navigation("Conta");

                    b.Navigation("Grupo");

                    b.Navigation("Parcelamento");
                });

            modelBuilder.Entity("Real.Models.Recorrencia", b =>
                {
                    b.HasOne("Real.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("Real.Models.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId");

                    b.Navigation("Categoria");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("Real.Models.Financa", b =>
                {
                    b.HasOne("Real.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("Real.Models.Recorrencia", "Recorrencia")
                        .WithMany("Repeticoes")
                        .HasForeignKey("RecorrenciaId");

                    b.Navigation("Categoria");

                    b.Navigation("Recorrencia");
                });

            modelBuilder.Entity("Real.Models.Grupo", b =>
                {
                    b.HasOne("Real.Models.Recorrencia", "Recorrencia")
                        .WithMany()
                        .HasForeignKey("RecorrenciaId");

                    b.Navigation("Recorrencia");
                });

            modelBuilder.Entity("Real.Models.Conta", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("Real.Models.Lancamento", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("Real.Models.Recorrencia", b =>
                {
                    b.Navigation("Repeticoes");
                });

            modelBuilder.Entity("Real.Models.Grupo", b =>
                {
                    b.Navigation("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
